### ISSUE TITLE
[Merge] `--squash` doesn't acutally squash

### ISSUE THREAD

**Issue by sstok** [park-manager/hubkit#64]
I just merged a pull request with the `--squash` option but still the commits were retained as-is, nothing was squashed. 

Not sure if this a bug in Hubkit or the GitHub API end-point.

**Comment by acrobat** [comment]
@sstok I've just hit the same bug while merging a PR. I was just checking the code, but isn't the bug here that the `--squash` option is not passed to the `mergePullRequest` method? (The parameter after the sha indicates a squash.

https://github.com/park-manager/hubkit/blob/master/src/Cli/Handler/MergeHandler.php#L89

**Comment by acrobat** [comment]
I've created a PR with a possible fix, see #74
